version: '3.6'

networks:
  graphql-net:
    driver: bridge

volumes:
  db_data:

services:
  postgres:
    image: postgres:12
    restart: on-failure
    ports:
      - 5432:5432
    networks:
     - graphql-net
    volumes:
     - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
  graphql-engine:
    image: hasura/graphql-engine:v1.1.0
    ports:
     - 8080:8080
    depends_on:
     - postgres
    restart: on-failure
    networks:
      - graphql-net
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DATABASE}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_GRAPHQL_ADMIN_SECRET
